[package]
name = "tui_lib"
version = "0.1.0"
edition = "2021"

[alias]
test = "test -- --test-threads=1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html